# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Cato
tagline:          'Cato using hydre theme'
description:      'A brazen two-column Cato try to run this blog'
url:              https://cato1718.github.io
baseurl:          /

author:
  name:           'Cato'
  url:            https://cato1718.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
